name: Test Quickstart in Services

on:
  push:
    branches: [main]

jobs:
  test:
    name: test services
    runs-on: ubuntu-22.04
    services:
      rpc:
        image: stellar/quickstart:testing
        ports:
        - 8000:8000
        env:
          # ENABLE_LOGS: true
          NETWORK: local
          ENABLE_SOROBAN_RPC: true
        options: >-
          --health-cmd "curl --no-progress-meter --fail-with-body -X GET 'http://localhost:8000'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v3
    - run: "curl --fail-with-body -X POST \"http://localhost:8000/soroban/rpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":8675309,\"method\":\"getNetwork\"}'"
    - run: curl --no-progress-meter "http://localhost:8000/friendbot?addr=$(./target/bin/soroban config identity address)"
